libraries <- c(
	"remotes"
	, "gsheet"
	, "shiny"
	, "shinyjs"
	, "shinyvalidate"
	, "shinyalert"
	, "shinyWidgets"
	, "shinydashboard"
	, "shinydashboardPlus"
	, "shinycssloaders"
	, "sjlabelled"
	, "dplyr"
	, "stringr"
	, "stringi"
	, "officer"
	, "readr"
	, "readxl"
	, "openxlsx"
	, "haven"
	, "forcats"
	, "skimr"
	, "summarytools"
	, "countries"
	, "plotly"
	, "RPostgreSQL"
	, "DT"
	, "bslib"
	, "gt"
	, "lubridate"
	, "gtsummary"
	, "webshot"
	, "webshot2"
	, "ggplot2"
	, "shinyFiles"
	, "flextable"
	, "RSQLite"
	, "sjmisc"
	, "DBI"
	, "RMySQL"
	, "remotes"
	, "Achilles"
	, "DatabaseConnector"
	, "doParallel"
	, "GGally"
	, "DataExplorer"
	, "htmltools"
	, "promises"
	, "future"
	, "CodelistGenerator"
	, "CDMConnector"
	, "CohortConstructor"
	, "RColorBrewer"
	, "caret"
	, "cli"
	, "fastshap"
	, "gemini.R"
	, "naniar"
	, "recipes"
	, "rlang"
	, "rsample"
	, "shapviz"
	, "callr"
	, "caretEnsemble"
	, "cvms"
	, "digest"
	, "foreach"
	, "ggthemes"
	, "grid"
	, "httpuv"
	, "httr"
	, "patchwork"
	, "pins"
	, "plumber"
	, "scales"
	, "themis"
	, "vetiver"
	, "waiter"
)


# Install missing CRAN packages
missing <- setdiff(libraries, rownames(installed.packages()))
if (length(missing) > 0) install.packages(missing, repos='https://cloud.r-project.org', dependencies = TRUE)

remotes::install_github("OHDSI/DataQualityDashboard")
remotes::install_github("jbryer/login")
